---
- hosts: all
  become: yes
  vars_files:
    - ../defaults/main.yml

  tasks:
    
    - name: Grab pvs
      shell: lsscsi |grep "VBOX HARDDISK"|grep -v "0:0:0"|awk '{print $7}'
      register: scsi_info
    
    
    - name: Create a partition 
      parted:
        device: "{{ item }}"
        label: gpt
        number: 1
        state: present
      with_items: "{{scsi_info.stdout_lines}}"
      register: pvs_info


    - name: Create a new  volume group
      lvg:
        vg: vg_database
        pvs: /dev/sdb1
        state: present
     
    - name: Create lots of logical volumes
      lvol:
        vg: vg_database
        lv: " {{ item.name }}"
        size: "{{ item.size }}" 
      with_items:
        - name: backup_lv
          size: 4g
      
    - name: Create xfs file systems
      filesystem:
        fstype: xfs
        dev: "/dev/mapper/vg_database-{{ item }}"
      with_items:
        - backup_lv

    - name: Mount file system
      mount:
        fstype: xfs
        path: "{{ backup_directory }}"
        src: "/dev/mapper/vg_database-{{ item }}"
        opts: noatime
        state: mounted
      with_items:
        - backup_lv
          
    - name: Rebooting...
      reboot:

    - shell: df -h
