---
- hosts: all
  become: yes
  vars_files:
    - ../defaults/main.yml

  tasks:
 
    - name: Install some basic packages
      yum:  
        name: ['telnet', 'net-tools', 'lvm2']

    - name: Add repo
      yum:
        name: https://download.postgresql.org/pub/repos/yum/{{ postgres_version}}/redhat/rhel-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm    
 
    - name: Install postgres and other deps
      yum: 
        name: "{{item}}" 
        state: present
      with_items:        
        - postgresql{{ postgres_version}}
        - postgresql{{ postgres_version}}-server
        - postgresql{{ postgres_version}}-libs
        - python-psycopg2

    - name: Initialize postgres db 
      command: /usr/pgsql-11/bin/postgresql-{{ postgres_version }}-setup initdb
  
    - name: Configure PostgreSQL host-based authentication
      template:
        src: ../templates/pg_hba.conf.j2
        dest: "/var/lib/pgsql/{{ postgres_version }}/data/pg_hba.conf"

    - name: "Start and enable services"
      service: 
        name: "{{ item }}" 
        state: started 
        enabled: yes
      with_items:
        - postgresql-{{ postgres_version}}
       
#      notify:
#        - restart postgresql

    - name: Configure PostgreSQL
      template:
        src: ../templates/postgresql.conf.j2 
        dest: "/var/lib/pgsql/{{ postgres_version }}/data/postgresql.conf"

    - name: "Restart services"
      service:
        name: "{{ item }}"
        state: restarted
      with_items:
        - postgresql-{{ postgres_version}}
     
