---
- hosts: all
  become: yes
  vars_files:
    - ../defaults/main.yml

  tasks:
  
    - name: pd reset database user
      become_method: sudo
      become_user: postgres
      postgresql_user: 
        name: postgres
        password: "{{ postgre_user }}"
        
    - name: "Create app database"
      postgresql_db:
        state: present
        name: "{{ db_name }}"
      become: yes
      become_user: postgres

    - name: "Create db user"
      postgresql_user:
        state: present
        name: "{{ db_user }}"
        password: "{{ db_password }}"
      become: yes
      become_user: postgres

    - name: "Grant db user access to db"
      postgresql_privs:
        type: database
        database: "{{ db_name }}"
        roles: "{{ db_user }}"
        grant_option: no
        privs: all
      become: yes
      become_user: postgres

    - name: Restarted postgres service
      service:
        name: postgresql-{{ postgres_version }}
        state: restarted


