---
- hosts: worker
  become: yes
  tasks:
    - name: Disable SELinux
      selinux:  
        state: disabled

    - name: Tuned Disable and Stop
      systemd:
        name: tuned
        state: stopped
        enabled: false


    - name: Rebooting
      reboot: 
