---
- hosts: all
  become: yes
  vars_files:
    - ../defaults/main.yml
    - ../defaults/repo_rhel.yml
  tasks:
 
    - name: Install some basic packages
      yum:  
        name: ['telnet', 'net-tools']
      
     
    - name: Install postgres RPM repo
      yum:
        name: "https://download.postgresql.org/pub/repos/yum/{{ postgres_version }}/redhat/rhel-{{ ansible_distribution_major_version }}-{{ ansible_architecture | lower }}/pgdg-redhat-repo-latest.noarch.rpm"
        state: present

    - name: Install postgres packages and other deps
      yum: 
        name: "{{item}}" 
        state: present
      with_items:
        - postgresql{{ postgres_version | replace('.', '') }}-server
        - postgresql{{ postgres_version | replace('.', '') }}-contrib
        - python-psycopg2
        - postgresql-libs
        - libselinux-python    
  
    #- name: "Install packages"
    #  yum:  
    #    name: "{{ item }}" 
    #    state: latest
    #  with_items:
    #    - postgresql
    #    - postgresql-server
    #    - python-psycopg2

    - name: Configure PostgreSQL host-based authentication
      template: 
        src: pg_hba.conf.j2 
        dest: /etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf
      notify:
        - Restart PostgreSQL

    - name: Configure PostgreSQL
      template: 
        src: postgresql.conf.j2 
        dest: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
      notify:
        - Restart PostgreSQL

    #- name: "Start and enable services"
    #  service: 
    #    name: "{{ item }}" 
    #    state: started 
    #    enabled: yes
    #  with_items:
    #    - postgresql
