# -*- mode: ruby -*-
# vi: set ft=ruby :

# README
#
# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. vagrant up
# 3. vagrant ssh
#
# This should put you at the control host
#  with access, by name, to other vms
Vagrant.configure(2) do |config|
  config.vm.define "control", primary: true do |h|
    h.vm.box = "centos/7"
    h.vm.hostname =  "control"
    h.vm.network "private_network", ip: "192.168.135.10"
    h.vm.network "forwarded_port", guest: 22, host: "2200", id: "ssh"
    h.vm.provision :shell, inline: "echo 'export ANSIBLE_CONFIG=/vagrant/ansible/ansible.cfg' >> /home/vagrant/.bash_profile"
    h.vm.provision "shell" do |provision|
      provision.path = "provision_ansible.sh"
    end 
  end

  config.vm.define "database" do |h|
    h.vm.box = "centos/7"
    h.vm.hostname = "database"
    h.vm.network "private_network", ip: "192.168.135.112"
    h.vm.network "forwarded_port", guest: 22, host: "2202", id: "ssh"
    h.vm.provision :shell, inline: 'test -e /usr/bin/python3 || (yum install -y python3)'
  end

end
