# -*- mode: ruby -*-
# vi: set ft=ruby :

# README
#
# Getting Started:
# 1. vagrant plugin install vagrant-hostmanager
# 2. vagrant up
# 3. vagrant ssh
#
# This should put you at the control host
#  with access, by name, to other vms
Vagrant.configure(2) do |config|
  config.vm.define "control", primary: true do |h|
    h.vm.box = "ubuntu/focal64"
    h.vm.hostname =  "control"
    h.vm.network "private_network", ip: "192.168.135.19"
    h.vm.network "forwarded_port", guest: 22, host: "2200", id: "ssh"
    h.vm.provision :shell, inline: "echo 'export ANSIBLE_CONFIG=/vagrant/ansible/ansible.cfg' >> /home/vagrant/.bash_profile"
    h.vm.provision "shell" do |provision|
      provision.path = "provision_ansible.sh"
    end 
  end

  config.vm.define "vm1" do |h|
    h.vm.box = "centos/7"
    h.vm.provider :virtualbox do |vm|
        vm.memory = 2048
        vm.cpus = 1#
    end 	  
    h.vm.hostname = "vm1"
    h.vm.network "private_network", ip: "192.168.135.12"
    h.vm.network "forwarded_port", guest: 22, host: "2202", id: "ssh"
    h.vm.provision :shell, inline: 'test -e /usr/bin/python3 || (yum install -y python3)'
  end
 
  config.vm.define "vm2" do |h|
    h.vm.box = "centos/7"
    h.vm.provider :virtualbox do |vm|
        vm.memory = 2048
        vm.cpus = 1
    end 
    h.vm.hostname = "vm2"
    h.vm.network "private_network", ip: "192.168.135.13"
    h.vm.network "forwarded_port", guest: 22, host: "2202", id: "ssh"
    h.vm.provision :shell, inline: 'test -e /usr/bin/python3 || (yum install -y python3)'
  end	

  config.vm.define "vm3" do |h|
    h.vm.box = "centos/7"
    h.vm.provider :virtualbox do |vm|
        vm.memory = 2048
        vm.cpus = 1
    end 
    h.vm.hostname = "vm3"
    h.vm.network "private_network", ip: "192.168.135.14"
    h.vm.network "forwarded_port", guest: 22, host: "2202", id: "ssh"
    h.vm.provision :shell, inline: 'test -e /usr/bin/python3 || (yum install -y python3)'
  end	
	
end
